# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']
future: true # Enable future posts (date > current date)


# Site Settings
title: "Research Bazaar Queensland"
email: "mailto:resbaz@qcif.edu.au"
description: "Run by a team of volunteers from south-east Queensland universities, Research Bazaar (ResBaz for short) is a skill- and community-building festival where students and researchers come together to learn the latest in digital research tools and digital scholarship."
baseurl: "/resbaz2026qld"
url: "https://resbaz.github.io/resbaz2026qld/"
permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "matty-plumski.github.io"
#siteVerification: "xOlzoaCacKCBpEsxW4st40F89pI="


# Organizer Info
organizerName: ""
organizerAlternateName: ""
# organizerDescription: " "
organizerEmail: "resbaz@qcif.edu.au" 
organizerLogo: "/img/seo/QCIF_Logo_web-copy.jpg"
organizerLink: "https://www.qcif.edu.au/"

# Head
metaKeywords: "conference, event, resbaz, research, bazaar, brisbane, meanjin, queensland, digital, skills, upskilling, hdr, ecr, eresearch, resbazqld, resbazbris"
twitterAccount: "@ResBazQld"
instagramAccount: "@ResBazQld"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"

# Documents
#c4pUrl: "mailto:"
c4sponsorsUrl: "https://www.qcif.edu.au"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/registration/", text: "Register"}
 #- {permalink: "/news/", text: "News"}
 #- {link: "https://forms.gle/5Kc4QUkhibvuopA48", text: "Get involved"}
 #- {link: "https://forms.gle/MQAHpunT1aCn7ueRA", text: "Keep me informed"}
 #- {permalink: "/schedule/", text: "Schedule"}
 #- {permalink: "/speakers/", text: "Speakers"}
 #- {permalink: "/sessions/", text: "Sessions"}
 - {permalink: "/transport/", text: "Getting here"}
 - {permalink: "/dietaries/", text: "Food"}
 # - {permalink: "/partners/", text: "Sponsors"}
 - {link: "https://www.linkedin.com/showcase/resbaz-qld", text: "Updates"}
 - {permalink: "/cod/", text: "Code of Conduct"}
   # bottomNavigationLinks:
  # - {link: "https://forms.gle/5Kc4QUkhibvuopA48", text: "Get involved - volunteer here!"}
#rightNavigationButtons:
# - {link: "https://forms.gle/5Kc4QUkhibvuopA48", text: "Get involved - volunteer here!"}

# Hero Block
heroImage: "ResBaz2026_Banner_v2.jpg"
#heroImage: "USC_Petrie_1.png"
heroTitle: "Research Bazaar Queensland"
eventDate: "23rd-25th Jun 2026 - QUT Kelvin Grove Campus"



# About Block
aboutTitle: "About ResBaz Queensland"
aboutSubtitle: "A festival of digital research"
aboutText: "<p>ResBaz is more than a conference - it's a three-day festival of digital research training, where researchers from all disciplines come together to learn new skills in an interactive, collaborative and - above all - fun setting. Featuring workshops, talks, discussion sessions, networking and plenty of social activities, ResBazQld provides participatory training spanning nearly fifty different topics of cutting-edge digital research tools and techniques.</p>

<p>Who should attend? Researchers at ALL levels from ALL disciplines. PhD candidates, research masters students and early career researchers are especially encouraged to attend. Research technologists and research software engineers who support researchers to do their job should also come along! Sessions at this year's ResBaz will offer a brief practical introduction to a broad selection of topics and tools related to digital research practice relevant across the disciplines. In the spirit of a marketplace or bazaar, ResBaz is a highly participatory event where researchers from many different disciplines can learn, share knowledge and skills, and have fun!</p>

<p>In 2026, ResBazQLD turns 10, and QUT is hosting for the first time. The <a href='https://www.usc.edu.au/study/life-at-unisc/study-locations/unisc-moreton-bay/about-unisc-moreton-bay-campus'>Moreton Bay campus</a> is UniSC's newest campus and is just 25 km north of the city centre. Find out <a href='/resbaz2026qld/transport/'>how to get there</a>.</p>"

# Statistic Block
# statisticBlockImage: "statistic.jpg"
# statisticBlock:
#  - {count: "100", specialCharacter: "+", info: "attendees", detail: ""}
#  - {count: "50", specialCharacter: "+", info: "hours", detail: ""}
#  - {count: "25", specialCharacter: "+", info: "speakers", detail: ""}
#  - {count: "3", specialCharacter: "", info: "parallel streams", detail: ""}

# Latest News Block
# latestNewsTitle: "Latest news"

# Rockstar Speakers Block
# rockstarSpeakersImage: "Wattle_ResbazQld_NathCampus.jpg"
# rockstarSpeakersCount: 3
# rockstarSpeakersTitle: "Keystory speakers"
# rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Queensland University of Technology - Kelvin Grove Campus"
eventLocationLink: "https://www.openstreetmap.org/relation/14524093#map=16/-27.45265/153.02002&layers=C"
eventStreetAddress: "149 Victoria Park Rd"
eventAddressLocality: "Kelvin Grove"
eventAddressLocalityRegion: "QLD"
eventPostalCode: "4059"
eventAddressCountry: "Australia"
eventStartTime: ""
eventDoorTime: ""
eventEndTime: ""
eventPlaceCoordinates: "-27.451870, 153.016495"
mapCenterCoordinates: "-27.451870, 153.016495"
mapMobileCenterCoordinates: "-27.451870, 153.016495"
#
# Venue Block
# venueBlockTitle: "Past Events"
# venueBigImage: "wisteria.jpg"
# venueSmallImage2: "wisteria.jpg"
# venueSmallImage1: "wisteria.jpg"
# venueSmallImage3: "wisteria.jpg"
# venueTitle: "ResBaz 2022 "
# venueFeatures: ["Mix of online and in-person events", "Network and collaborate","Sessions streamed across Queensland"]

# Tweets Feed Block
tweetsFeedImage: "PurpleF_ResbazQld_NathCampus.jpg"
tweetsFeedTitle: "What's the latest?"
twitterHashTag: "ResBazQld"
twitterFeed: "https://twitter.com/ResBazQld"

# Partners Block
# organizersTitle: "Organisers"
# partnersTitle: "Partners"
# partnersC4sponsorsButton: "See you next year!"
# partnersLink: ""

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://docs.google.com/forms/d/e/1FAIpQLSfTwkZaRlKULFQrnY66P2MJSpYeUyS2eJ3RPcqMDNHy1QxmyA/viewform"
# subscribeInfo: ""

# Tickets Block
# ticketsTitle: "Pricetable"
# ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
# ticketsOffers: -
#  name: "Early Bird"
#   price: " "
#  priceCurrency: " "
#  ticketsNumber: " "
#  ribbon: "-5%"
#   buyButtonLink: " "
#  buyButtonText: " "
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-25T10:00"
# validThrough: "2014-09-30T23:59"
#  -
#   name: "Last Chance"
#   price: " "
#  priceCurrency: " "
#   ticketsNumber: " "
#   ribbon: "-20%"
#  featured: true
#   buyButtonLink: " "
#   buyButtonText: "Buy Now"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-10-01T00:00"
#   validThrough: "2014-10-23T23:59"
#   disabled: true
# -
#   name: "Student"
#   price: " "
#   priceCurrency: " "
#   ticketsNumber: " "
#   buyButtonLink: " /"
#   buyButtonText: "Buy Now"
#   additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-20T10:00"
#  validThrough: "2014-10-23T23:59"
#  soldOut: true
#   soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://bne.social/@resbazqld", icon: "mastodon"}
 - {link: "https://instagram.com/ResBazQld", icon: "instagram"}
 - {link: "https://www.linkedin.com/showcase/resbaz-qld", icon: "linkedin"}
 - {link: "https://www.qcif.edu.au/", icon: "site"}
 - {link: "https://github.com/resbaz/resbaz2026qld", icon: "github"}
 - {link: "https://forms.gle/5Kc4QUkhibvuopA48", icon: "mail"}
footerBlocks:
 -
  #title: "Logo Customisation"
#  links:
#   - {link: "https://www.linkedin.com/in/alexandra-gloria-9b703814a/", text: "Logo customisations by Alex Gloria"}
 -
#  title: "National ResBaz Sponsors"
#  links:
#   - {link: "https://www.gale.com/intl/primary-sources/digital-scholar-lab", text: "Gale", imageUrl: "../img/organizers/gale_trans.png"}
#   - {link: "https://ardc.edu.au", text: "ARDC", imageUrl: "../img/organizers/ARDC_logo_RGB.png"}
 -
  title: "Gold Sponsors"
  #links:
   #- {link: "https://ardc.edu.au", text: "ARDC", imageUrl: "../img/organizers/ARDC_logo_RGB.png"}
#   - {link: "https://taylorandfrancis.com/", text: "Taylor & Francis", imageUrl: "../img/organizers/TaylorFrancisLogo.png"}
 -    
  title: "Silver Sponsor"
  #links:
    #- {link: "https://aarnet.edu.au/", text: "AARNet", imageUrl: "../img/organizers/aarnet.png"}
    #- {link: "https://www.springernature.com/gp", text: "Springer Nature", imageUrl: "../img/organizers/logo-springernature.svg"}
 -  
  title: "Collaborating Institutes"
  links:
   - {text: "ACU", description: "ACU", link: "https://www.acu.edu.au/", imageUrl: "../img/organizers/acu_logo_purple.svg"}
   - {text: "The University of Queensland", description: "UQ", link: "https://www.uq.edu.au/", imageUrl: "../img/organizers/uq.jpg"}
   - {text: "QCIF", link: "https://www.qcif.edu.au/", imageUrl: "../img/organizers/QCIF_Logo_Master.png"}
   - {link: "griffith.edu.au", text: "Griffith University", imageUrl: "../img/organizers/GU.gif"}
   - {text: "QUT", description: "QUT", link: "https://www.qut.edu.au/", imageUrl: "../img/organizers/QUT.gif"}
   - {text: "UniSC", description: "Sunshine Coast Uni", link: "https://www.usc.edu.au/", imageUrl: "../img/organizers/USC_Name.PNG"}
 -  
  title: "Contacts"
  links:
   - {link: "mailto:resbaz@qcif.edu.au", text: "resbaz@qcif.edu.au"}
  # - {link: "https://forms.gle/5Kc4QUkhibvuopA48", text: "Volunteer as a helper for ResBaz"}
  # - {link: "https://forms.gle/xxukxNN5FNFMEoZV9", text: "Submit a workshop for ResBaz"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
# blogTitle: "Latest news"
# blogCommentsEnabled: false
# discusShortName: "resbazqld"

# Speakers List Block
showSessions: true
showSpeakersBioFirst: true
